In [1]:
# IMPORT Everything here
import pandas as pd
import matplotlib.pyplot as plt
import scipy.stats as st
import numpy as np
import requests
from Iconfig import api_Key
from Iconfig import api_READ_token
import json

In [10]:
# URL for GET requests to retrieve movie data

url = "https://api.themoviedb.org/3/search/movie?query=the&primary_release_year=2022"

headers = {
    "accept": "application/json",
    "Authorization": f"Bearer {api_READ_token}" 
}

movieData2022 = requests.get(url, headers=headers)

movieData2022_json = movieData2022.json()






url = "https://api.themoviedb.org/3/search/movie?query=the&primary_release_year=2021"

headers = {
    "accept": "application/json",
    "Authorization": f"Bearer {api_READ_token}" 
}

movieData2021 = requests.get(url, headers=headers)

movieData2021_json = movieData2021.json()







url = "https://api.themoviedb.org/3/search/movie?query=the&primary_release_year=2020"

headers = {
    "accept": "application/json",
    "Authorization": f"Bearer {api_READ_token}" 
}

movieData2020 = requests.get(url, headers=headers)

movieData2020_json = movieData2020.json()






url = "https://api.themoviedb.org/3/search/movie?query=the&primary_release_year=2019"

headers = {
    "accept": "application/json",
    "Authorization": f"Bearer {api_READ_token}" 
}

movieData2019 = requests.get(url, headers=headers)

movieData2019_json = movieData2019.json()






url = "https://api.themoviedb.org/3/search/movie?query=the&primary_release_year=2018"

headers = {
    "accept": "application/json",
    "Authorization": f"Bearer {api_READ_token}" 
}

movieData2018 = requests.get(url, headers=headers)

movieData2018_json = movieData2018.json()

In [11]:
dataCACHED2022 = movieData2022_json

dataCACHED2021 = movieData2021_json

dataCACHED2020 = movieData2020_json

dataCACHED2019 = movieData2019_json

dataCACHED2018 = movieData2018_json

In [12]:
#Scrape info we need (title, audience score, box office, etc.)

### The results DID NOT include Box-Office results or Budget. ###

movie_names2022 = []
audience_score2022 = []
popularity2022 = []


for i in range(0, len(dataCACHED2022["results"])):
    movie_names2022.append(dataCACHED2022["results"][i]["title"])
    audience_score2022.append(dataCACHED2022["results"][i]["vote_average"])
    popularity2022.append(dataCACHED2022["results"][i]["popularity"])

movieData2022_df = pd.DataFrame({
    "Name": movie_names2022,
    "Audience Score": audience_score2022,
    "Popularity": popularity2022
})






movie_names2021 = []
audience_score2021 = []
popularity2021 = []

for i in range(0, len(dataCACHED2021["results"])):
    movie_names2021.append(dataCACHED2021["results"][i]["title"])
    audience_score2021.append(dataCACHED2021["results"][i]["vote_average"])
    popularity2021.append(dataCACHED2021["results"][i]["popularity"])

movieData2021_df = pd.DataFrame({
    "Name": movie_names2021,
    "Audience Score": audience_score2021,
    "Popularity": popularity2021
})







movie_names2020 = []
audience_score2020 = []
popularity2020 = []

for i in range(0, len(dataCACHED2020["results"])):
    movie_names2020.append(dataCACHED2020["results"][i]["title"])
    audience_score2020.append(dataCACHED2020["results"][i]["vote_average"])
    popularity2020.append(dataCACHED2020["results"][i]["popularity"])

movieData2020_df = pd.DataFrame({
    "Name": movie_names2020,
    "Audience Score": audience_score2020,
    "Popularity": popularity2020
})







movie_names2019 = []
audience_score2019 = []
popularity2019 = []

for i in range(0, len(dataCACHED2019["results"])):
    movie_names2019.append(dataCACHED2019["results"][i]["title"])
    audience_score2019.append(dataCACHED2019["results"][i]["vote_average"])
    popularity2019.append(dataCACHED2019["results"][i]["popularity"])

movieData2019_df = pd.DataFrame({
    "Name": movie_names2019,
    "Audience Score": audience_score2019,
    "Popularity": popularity2019
})







movie_names2018 = []
audience_score2018 = []
popularity2018 = []

for i in range(0, len(dataCACHED2018["results"])):
    movie_names2018.append(dataCACHED2018["results"][i]["title"])
    audience_score2018.append(dataCACHED2018["results"][i]["vote_average"])
    popularity2018.append(dataCACHED2018["results"][i]["popularity"])

movieData2018_df = pd.DataFrame({
    "Name": movie_names2018,
    "Audience Score": audience_score2018,
    "Popularity": popularity2018
})

In [13]:
movieData2022_df.head(20)

,Name,Audience Score,Popularity
0,Avatar: The Way of Water,7.670,705.015
1,The Last Heretic,5.458,55.935
2,Shark Side of the Moon,5.201,125.016
3,Puss in Boots: The Last Wish,8.275,492.943
4,The Simpsons Meet the Bocellis in Feliz Navidad,5.973,55.077
5,Ghosts of the Ozarks,5.714,26.173
6,The First Slam Dunk,8.046,97.796
7,Sword Art Online the Movie -Progressive- Scher...,7.698,236.070
8,The Next 365 Days,6.447,154.334
9,The Surprise Visit,5.214,19.572
10,Sonic the Hedgehog 2,7.589,219.535
11,Sniper: The White Raven,7.551,239.287
12,Encanto at the Hollywood Bowl,7.041,129.246
13,The Darker the Lake,5.300,24.386
14,Prizefighter: The Life of Jem Belcher,6.305,137.015
15,The Batman,7.714,232.489
16,The Whale,7.994,190.695
17,Roald Dahl's Matilda the Musical,6.773,132.791
18,Lord of the Streets,5.200,61.998
19,The Exorcism of God,7.159,116.605

In [14]:
movieData2021_df.head(20)

,Name,Audience Score,Popularity
0,The Conjuring: The Devil Made Me Do It,7.515,768.730
1,Mortal Kombat Legends: Battle of the Realms,7.800,501.720
2,Demon Slayer: Kimetsu no Yaiba the Hashira Mee...,7.200,179.945
3,Aria the Benedizione,6.300,13.572
4,PAW Patrol: The Movie,7.431,320.610
5,Ryoma! The Prince of Tennis,5.300,61.108
6,The Penitent Thief,6.071,62.755
7,Rurouni Kenshin: The Beginning,7.651,51.590
8,Venom: Let There Be Carnage,6.850,138.623
9,Rock Dog 2: Rock Around the Park,6.619,26.730
10,Legend Quest: The Origin,8.220,132.653
11,The Suicide Squad,7.572,168.039
12,Rurouni Kenshin: The Final,7.782,49.741
13,Shang-Chi and the Legend of the Ten Rings,7.601,112.688
14,To Kill the Beast,6.100,46.010
15,Miraculous World: Shanghai – The Legend of Lad...,7.873,108.176
16,Clifford the Big Red Dog,7.221,88.056
17,The Boss Baby: Family Business,7.452,97.637
18,Pushpa: The Rise - Part 1,7.274,24.054
19,The Simpsons in Plusaversary,6.543,46.194

In [15]:
movieData2020_df.head(20)

,Name,Audience Score,Popularity
0,Demon Slayer -Kimetsu no Yaiba- The Movie: Mug...,8.300,142.816
1,Making The Witcher,7.152,53.180
2,Grisaia: Phantom Trigger The Animation - Starg...,6.350,33.355
3,The Owners,5.727,14.589
4,Deathstroke: Knights & Dragons - The Movie,7.001,116.241
5,The Croods: A New Age,7.519,83.858
6,Sonic the Hedgehog,7.352,93.032
7,The Call of the Wild,7.570,37.933
8,The SpongeBob Movie: Sponge on the Run,7.529,88.612
9,Birds of Prey (and the Fantabulous Emancipatio...,6.968,100.893
10,Enter the Fat Dragon,6.337,14.049
11,The Kissing Booth 2,7.715,36.930
12,The Wishmas Tree,6.450,21.163
13,The Silencing,6.504,70.072
14,Pokémon the Movie: Secrets of the Jungle,7.154,48.279
15,Roald Dahl's The Witches,6.405,76.189
16,The Stranger by the Shore,7.600,44.077
17,Lucy Shimmers And The Prince Of Peace,8.521,17.785
18,Violet Evergarden: The Movie,8.330,48.252
19,The Yin-Yang Master: Dream of Eternity,7.431,20.520

In [16]:
movieData2019_df.head(20)

,Name,Audience Score,Popularity
0,The Art of Racing in the Rain,8.221,80.325
1,The Lion King,7.129,93.353
2,The Pilgrim's Progress,7.657,50.517
3,How to Train Your Dragon: The Hidden World,7.765,79.566
4,"The Gangster, the Cop, the Devil",7.753,55.912
5,Lupin III: The First,7.394,18.023
6,Psycho-Pass: Sinners of the System - Case.1 C...,6.700,19.346
7,Jumanji: The Next Level,6.937,69.720
8,The Legend of the Galactic Heroes: Die Neue Th...,7.800,2.990
9,Star Wars: The Rise of Skywalker,6.380,56.618
10,The Operative,5.850,19.621
11,The Platform,6.989,43.769
12,Psycho-Pass: Sinners of the System - Case.2 Fi...,6.800,15.481
13,Godzilla: King of the Monsters,6.675,69.875
14,The Curse of La Llorona,5.704,59.028
15,Pokémon the Movie: Mewtwo Strikes Back - Evolu...,6.709,49.456
16,The Little Mermaid Live!,7.256,28.708
17,The Addams Family,6.617,51.435
18,The Nest,6.277,8.330
19,Red Shoes and the Seven Dwarfs,7.761,48.906

In [17]:
movieData2018_df.head(20)

                                 Name  Audience Score  Popularity
0                   The Darkest Minds           7.035     968.271
1             Insidious: The Last Key           6.268     900.611
2   Spider-Man: Into the Spider-Verse           8.400     299.613
3                  The Little Mermaid           5.000      66.306
4                             The Meg           6.232     260.941
5                   The Kissing Booth           7.238      63.340
6         Maze Runner: The Death Cure           7.111      58.206
7                             The Nun           5.855     101.091
8         Sicario: Day of the Soldado           6.889      57.940
9                     The Equalizer 2           6.690      79.977
10             The Night Comes for Us           6.827      14.307
11                       The Predator           5.625      94.838
12          Ralph Breaks the Internet           7.210      55.593
13                    The First Purge           5.988      62.130
14                         The Grinch           6.828      53.886
15  To All the Boys I've Loved Before           7.649      43.351
16               Ant-Man and the Wasp           6.953      49.806
17  The Witch: Part 1. The Subversion           7.800      38.498
18        The Second Coming of Christ           3.600      11.351
19                           The Pool           6.058      14.404